spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_eleves
    username: gestion_eleves
    password: gestion_eleves

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080